/*
 * generated by Xtext 2.12.0
 */
package x.buglang.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import x.buglang.ui.internal.BuglangActivator;

public class BugslyUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BuglangActivator.getInstance().getInjector("x.buglang.Bugsly");
	}

}
