/*
 * generated by Xtext 2.12.0
 */
package x.buglang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BugslyStandaloneSetup extends BugslyStandaloneSetupGenerated {

	def static void doSetup() {
		new BugslyStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
