/*
 * generated by Xtext 2.12.0
 */
package x.buglang.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import x.buglang.ui.internal.BuglangActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BugslyExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BuglangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BuglangActivator.getInstance().getInjector(BuglangActivator.X_BUGLANG_BUGSLY);
	}
	
}
