/*
 * generated by Xtext 2.12.0
 */
package x.buglang.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import x.buglang.BugslyRuntimeModule
import x.buglang.BugslyStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class BugslyIdeSetup extends BugslyStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new BugslyRuntimeModule, new BugslyIdeModule))
	}
	
}
