/*
 * generated by Xtext 2.12.0
 */
package x.buglang.scoping;

import org.eclipse.xtext.xbase.annotations.typesystem.XbaseWithAnnotationsBatchScopeProvider;

public abstract class AbstractBugslyScopeProvider extends XbaseWithAnnotationsBatchScopeProvider {
}
